@extends('layouts.app')
@section('header', 'Reports')
@section('content')
<div class="space-y-6 animate-fade-in">
    <h2 class="text-xl font-bold">Reports & Export</h2>
    <div class="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <div class="glass rounded-xl p-6">
            <h3 class="font-semibold mb-4 flex items-center gap-2"><svg class="w-5 h-5 text-rose-400" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 21h10a2 2 0 002-2V9.414a1 1 0 00-.293-.707l-5.414-5.414A1 1 0 0012.586 3H7a2 2 0 00-2 2v14a2 2 0 002 2z"/></svg> Generate PDF Report</h3>
            <form method="POST" action="{{ route('reports.pdf') }}" class="space-y-4">
                @csrf
                <div><label class="block text-sm text-slate-400 mb-1">Resource</label><select name="resource_id" class="form-input"><option value="">All Resources</option>@foreach(\App\Models\Resource::orderBy('title')->get() as $r)<option value="{{ $r->id }}">{{ $r->title }}</option>@endforeach</select></div>
                <button type="submit" class="btn btn-primary w-full">Generate PDF</button>
            </form>
        </div>
        <div class="glass rounded-xl p-6">
            <h3 class="font-semibold mb-4 flex items-center gap-2"><svg class="w-5 h-5 text-emerald-400" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 10h18M3 14h18m-9-4v8m-7 0h14a2 2 0 002-2V8a2 2 0 00-2-2H5a2 2 0 00-2 2v8a2 2 0 002 2z"/></svg> Export CSV</h3>
            <form method="POST" action="{{ route('reports.csv') }}" class="space-y-4">
                @csrf
                <div><label class="block text-sm text-slate-400 mb-1">Subject Filter</label><select name="subject" class="form-input"><option value="">All Subjects</option>@foreach(\App\Models\Resource::SUBJECTS as $s)<option value="{{ $s }}">{{ $s }}</option>@endforeach</select></div>
                <button type="submit" class="btn btn-success w-full">Export CSV</button>
            </form>
        </div>
    </div>
    <div class="glass rounded-xl p-6">
        <h3 class="font-semibold mb-4">Report History</h3>
        <div class="table-container">
            <table class="data-table"><thead><tr><th>Type</th><th>Title</th><th>Generated By</th><th>Date</th><th></th></tr></thead>
            <tbody>
            @forelse($reports as $report)
            <tr><td><span class="px-2 py-0.5 rounded text-xs font-semibold {{ $report->type == 'pdf' ? 'bg-rose-500/20 text-rose-300' : 'bg-emerald-500/20 text-emerald-300' }}">{{ strtoupper($report->type) }}</span></td><td>{{ $report->title }}</td><td class="text-slate-400">{{ $report->generatedBy->name }}</td><td class="text-slate-400 text-sm">{{ $report->created_at->format('M d, Y') }}</td><td>@if($report->file_path)<a href="{{ route('reports.download', $report) }}" class="text-indigo-400 hover:text-indigo-300 text-sm">Download</a>@endif</td></tr>
            @empty
            <tr><td colspan="5" class="text-center py-6 text-slate-400">No reports generated yet</td></tr>
            @endforelse
            </tbody></table>
        </div>
        @if($reports->hasPages())<div class="pagination-wrapper mt-4">{{ $reports->links() }}</div>@endif
    </div>
</div>
@endsection
