@extends('layouts.app')
@section('header', 'Reports')
@section('content')
<div class="space-y-6 animate-fade-in">
    <h2 class="text-lg font-bold font-heading text-forest">Reports & Export</h2>
    <div class="grid grid-cols-1 lg:grid-cols-2 gap-4">
        <div class="glass-card p-5">
            <h3 class="text-base font-bold font-heading mb-4 flex items-center gap-2"><svg class="w-5 h-5 text-forest" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 21h10a2 2 0 002-2V9.414a1 1 0 00-.293-.707l-5.414-5.414A1 1 0 0012.586 3H7a2 2 0 00-2 2v14a2 2 0 002 2z"/></svg> Generate PDF Report</h3>
            <form method="POST" action="{{ route('reports.pdf') }}" class="space-y-4">
                @csrf
                <div><label class="block text-sm font-medium text-forest/70 mb-1">Resource</label><select name="resource_id" class="form-input text-forest"><option value="">All Resources</option>@foreach(\App\Models\Resource::orderBy('title')->get() as $r)<option value="{{ $r->id }}">{{ $r->title }}</option>@endforeach</select></div>
                <button type="submit" class="btn btn-primary w-full shadow-sm">Generate PDF</button>
            </form>
        </div>
        <div class="glass-card p-5">
            <h3 class="text-base font-bold font-heading mb-4 flex items-center gap-2"><svg class="w-5 h-5 text-forest" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 10h18M3 14h18m-9-4v8m-7 0h14a2 2 0 002-2V8a2 2 0 00-2-2H5a2 2 0 00-2 2v8a2 2 0 002 2z"/></svg> Export CSV</h3>
            <form method="POST" action="{{ route('reports.csv') }}" class="space-y-4">
                @csrf
                <div><label class="block text-sm font-medium text-forest/70 mb-1">Subject Filter</label><select name="subject" class="form-input text-forest"><option value="">All Subjects</option>@foreach(\App\Models\Resource::SUBJECTS as $s)<option value="{{ $s }}">{{ $s }}</option>@endforeach</select></div>
                <button type="submit" class="btn btn-secondary w-full shadow-sm bg-white hover:text-white">Export CSV</button>
            </form>
        </div>
    </div>
    <div class="glass-card p-5">
        <h3 class="text-base font-bold font-heading mb-4 text-forest">Report History</h3>
        <div class="table-container">
            <table class="data-table"><thead><tr><th>Type</th><th>Title</th><th>Generated By</th><th>Date</th><th></th></tr></thead>
            <tbody>
            @forelse($reports as $report)
            <tr><td><span class="px-2 py-0.5 rounded text-xs font-semibold {{ $report->type == 'pdf' ? 'bg-forest/10 text-forest' : 'bg-emerald-500/10 text-emerald-700' }}">{{ strtoupper($report->type) }}</span></td><td>{{ $report->title }}</td><td class="text-forest/60">{{ $report->generatedBy->name }}</td><td class="text-forest/60 text-sm">{{ $report->created_at->format('M d, Y') }}</td><td>@if($report->file_path)<a href="{{ route('reports.download', $report) }}" class="text-forest hover:text-forest-dark font-medium text-sm">Download</a>@endif</td></tr>
            @empty
            <tr><td colspan="5" class="text-center py-6 text-forest/50">No reports generated yet</td></tr>
            @endforelse
            </tbody></table>
        </div>
        @if($reports->hasPages())<div class="pagination-wrapper mt-4">{{ $reports->links() }}</div>@endif
    </div>
</div>
@endsection
